
#ifndef WORDUTATE_CONFIG_HPP_
#define WORDUTATE_CONFIG_HPP_

#define WORDUTATE_ALLOCATOR std::allocator
#define DUCT_CONFIG_ALLOCATOR WORDUTATE_ALLOCATOR

#include <duct/config.hpp>

#endif // WORDUTATE_CONFIG_HPP_
