
#ifndef WORDUTATE_CONFIG_HPP_
#define WORDUTATE_CONFIG_HPP_

#define WORDUTATE_CONFIG_STL_ALLOCATOR std::allocator
#define DUCT_CONFIG_STL_ALLOCATOR WORDUTATE_CONFIG_STL_ALLOCATOR

#include <duct/config.hpp>

#endif // WORDUTATE_CONFIG_HPP_
